version: '3.1'

services:
  web:
    build: 
      context: ./client
    ports:
      - 80:3000
    volumes:
      - ./client:/app
    depends_on:
      - server
    environment:
      API_HOST: http://local.io
      API_PORT: 8000
    command: npm start

  server:
    build:
      context: ./server
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./server:/app
    environment:
      APP_NAME: Todo API
      APP_ENV: local
      APP_KEY: 12341234123412341234123412341234
      APP_DEBUG: 1
      APP_URL: http://local.io
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: onlinemeded
      DB_USERNAME: phpuser
      DB_PASSWORD: development
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
    restart: always
    environment:
      MYSQL_DATABASE: onlinemeded
      MYSQL_USER: phpuser
      MYSQL_PASSWORD: development
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 8001:3306
