version: '3.1'

services:
  web:
    build:
      context: ./server
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./server:/app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: onlinemeded
      DATABASE_USER: phpuser
      DATABASE_PASSWORD: development
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
    restart: always
    environment:
      MYSQL_DATABASE: onlinemeded
      MYSQL_USER: phpuser
      MYSQL_PASSWORD: development
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 8001:3306
